#define LED_PORT_DIR	P5DIR
#define LED_PORT_OUT	P5OUT
#define RED_LED			BIT1
#define GREEN_LED		BIT0

#define INIT_LEDS()		LED_PORT_DIR |= RED_LED + GREEN_LED
#define RED_ON()		LED_PORT_OUT |= RED_LED
#define GREEN_ON()		LED_PORT_OUT |= GREEN_LED
#define RED_OFF()		LED_PORT_OUT &= ~RED_LED
#define GREEN_OFF()		LED_PORT_OUT &= ~GREEN_LED
#define SWITCH_RED()	LED_PORT_OUT ^= RED_LED
#define SWITCH_GREEN()	LED_PORT_OUT ^= GREEN_LED
